### ISSUE TITLE
f-droid build failing

### ISSUE THREAD

**Issue by kmac** [kmac/mindfulnotifier#45]
The f-droid build is failing. From searching the error it looks like we need to force the f-droid build from JDK 8 to 11.

Failure snippet (full log at https://monitor.f-droid.org/builds/log/com.kmac5dev.mindfulnotifier/39):

```
Installing Android SDK Platform 30 in /opt/android-sdk/platforms/android-30
"Install Android SDK Platform 30 (revision: 3)" complete.
"Install Android SDK Platform 30 (revision: 3)" finished.
An exception has occurred in the compiler (1.8.0_302). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)
	at com.sun.tools.javac.util.Assert.error(Assert.java:133)
	at com.sun.tools.javac.code.TypeAnnotations.annotationType(TypeAnnotations.java:231)
	at com.sun.tools.javac.code.TypeAnnotations$TypeAnnotationPositions.separateAnnotationsKinds(TypeAnnotations.java:294)
	...
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android_alarm_manager_plus:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 39s
Running Gradle task 'assembleRelease'...                          104.7s
Gradle task assembleRelease failed with exit code 1
2021-11-21 18:53:26,042 ERROR: Could not build app com.kmac5dev.mindfulnotifier: Error running build command for com.kmac5dev.mindfulnotifier:1.0.20
```

**Comment by kmac** [comment]
Fixed by linsui in commit https://gitlab.com/fdroid/fdroiddata/-/commit/b8c71f30857a1db6a7520dbea4cb9cc0dcaedd4c
